### ISSUE TITLE
Issue with installing theme

### ISSUE THREAD

**Issue by schtinkafinga** [axelrindle/h5ai-theme-papirus#1]
OS: Ubuntu 20.04
After using `npm install`

``root@secured:~/h5ai-theme-papirus# sudo ./cli.js /home/s1/public_html/_h5ai``
``sudo: ./cli.js: command not found``

**Comment by axelrindle** [comment]
Please try the following:

```shell
sudo node cli.js /home/s1/public_html/_h5ai
```
